import { DeckSpec, ThemePreset } from '../dsl/schema'

const OPENROUTER_API = 'https://openrouter.ai/api/v1/chat/completions'
const DEFAULT_MODEL = 'openai/gpt-4o-mini'

function getAPIKey(): string | null {
  return localStorage.getItem('slidelang_api_key') || null
}

function getModel(): string {
  return localStorage.getItem('slidelang_model') || DEFAULT_MODEL
}

const SYSTEM_PROMPT = `You are Slidelang, a deck specification generator. 
Given a user's topic prompt, generate a complete deck specification as JSON.

The deck spec schema is:
{
  meta: { title, author?, date?, theme: "default"|"dark"|"minimal"|"gradient"|"corporate", description? },
  slides: [
    {
      kind: "title"|"section"|"content"|"two-column"|"image-full"|"quote"|"comparison"|"chart"|"math"|"blank",
      title?, subtitle?,
      blocks: [
        { type: "text", content: string, style?: { bold?, italic?, size?: "small"|"medium"|"large"|"xlarge", color?, align? } },
        { type: "bullets"|"numbered", items: string[] },
        { type: "chart", chartType: "bar"|"line"|"pie"|"area", title?, labels: string[], datasets: [{ label: string, values: number[], color? }] },
        { type: "math", expression: string, inline?: boolean },
        { type: "image", source: { url: string, alt?, caption?, width?, height? }, fit? }
      ],
      background?, notes?, layoutIssues?
    }
  ]
}

Rules:
1. Generate 4-8 slides for a standard deck, 8-12 for a detailed one.
2. Use a title slide first, then section/content slides.
3. Include at least one chart block with realistic data.
4. Include at least one math block with a relevant formula.
5. Include at least one image block with a placeholder URL from picsum.photos.
6. Use two-column slides for comparisons, content slides for explanations.
7. Make the content substantive and realistic — not generic filler.
8. For math: use LaTeX expressions without delimiters.
9. For charts: provide realistic labels and values.
10. Return ONLY valid JSON — no markdown, no explanation.`

export async function planDeck(prompt: string): Promise<DeckSpec> {
  const apiKey = getAPIKey()
  if (!apiKey) {
    return generateFallbackDeck(prompt)
  }

  try {
    const response = await fetch(OPENROUTER_API, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'HTTP-Referer': window.location.origin,
        'X-Title': 'Slidelang',
      },
      body: JSON.stringify({
        model: getModel(),
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: prompt },
        ],
        temperature: 0.7,
        max_tokens: 4096,
        response_format: { type: 'json_object' },
      }),
    })

    if (!response.ok) {
      throw new Error(`API error: ${response.status} ${response.statusText}`)
    }

    const data = await response.json()
    const content = data.choices?.[0]?.message?.content
    if (!content) {
      throw new Error('No content in response')
    }

    const spec = JSON.parse(content) as DeckSpec
    validateSpec(spec)
    return spec
  } catch (err) {
    console.warn('AI planning failed, using fallback:', err)
    return generateFallbackDeck(prompt)
  }
}

function validateSpec(spec: DeckSpec): void {
  if (!spec.meta) spec.meta = { title: 'Untitled Deck', theme: 'default' }
  if (!spec.meta.theme) spec.meta.theme = 'default'
  if (!Array.isArray(spec.slides)) {
    spec.slides = []
  }
  spec.slides.forEach((slide, i) => {
    if (!slide.kind) slide.kind = 'content'
    if (!Array.isArray(slide.blocks)) slide.blocks = []
  })
}

function generateFallbackDeck(prompt: string): DeckSpec {
  const title = prompt.length > 60 ? prompt.slice(0, 60) + '...' : prompt
  return {
    meta: { title, theme: 'default', date: new Date().toISOString().slice(0, 10) },
    slides: [
      {
        kind: 'title',
        title,
        subtitle: 'Generated by Slidelang',
        blocks: [
          { type: 'text', content: 'An AI-assisted deck-as-code presentation', style: { italic: true, size: 'large' } },
        ],
      },
      {
        kind: 'content',
        title: 'Overview',
        blocks: [
          { type: 'bullets', items: ['Generated from your prompt', 'Editable deck specification', 'Structured slide content', 'Charts, math, and images supported'] },
        ],
      },
      {
        kind: 'chart',
        title: 'Key Metrics',
        blocks: [
          {
            type: 'chart',
            chartType: 'bar',
            title: 'Sample Data',
            labels: ['Q1', 'Q2', 'Q3', 'Q4'],
            datasets: [
              { label: 'Revenue', values: [120, 195, 170, 240], color: '#4361ee' },
              { label: 'Costs', values: [80, 110, 95, 130], color: '#f72585' },
            ],
          },
        ],
      },
      {
        kind: 'math',
        title: 'Growth Formula',
        blocks: [
          { type: 'math', expression: '\\text{Growth Rate} = \\frac{V_{\\text{final}} - V_{\\text{initial}}}{V_{\\text{initial}}} \\times 100\\%' },
          { type: 'math', expression: '\\text{ROI} = \\frac{\\text{Gain} - \\text{Cost}}{\\text{Cost}}' },
          { type: 'text', content: 'Apply these formulas to track performance metrics across quarters.', style: { size: 'medium' } },
        ],
      },
      {
        kind: 'two-column',
        title: 'Comparison',
        blocks: [
          { type: 'text', content: 'Approach A', style: { bold: true, size: 'xlarge' } },
          { type: 'bullets', items: ['Low initial cost', 'Slater scale-up', 'Easier maintenance', 'Limited flexibility'] },
          { type: 'text', content: 'Approach B', style: { bold: true, size: 'xlarge' } },
          { type: 'bullets', items: ['Higher upfront investment', 'Faster scaling', 'More flexible', 'Requires expertise'] },
        ],
      },
      {
        kind: 'image-full',
        title: 'Visual Reference',
        blocks: [
          { type: 'image', source: { url: 'https://picsum.photos/seed/' + encodeURIComponent(prompt.slice(0, 20)) + '/800/400', alt: 'Related visual', caption: 'Reference image' } },
        ],
      },
      {
        kind: 'content',
        title: 'Next Steps',
        blocks: [
          { type: 'numbered', items: ['Review and edit slide content', 'Customize theme and layout', 'Add your own data and visuals', 'Export and share your deck'] },
        ],
      },
    ],
  }
}

export function isAIConfigured(): boolean {
  return !!localStorage.getItem('slidelang_api_key')
}

export function setAIConfig(apiKey: string, model?: string): void {
  localStorage.setItem('slidelang_api_key', apiKey)
  if (model) localStorage.setItem('slidelang_model', model)
}

export function clearAIConfig(): void {
  localStorage.removeItem('slidelang_api_key')
  localStorage.removeItem('slidelang_model')
}
